// Decompiled with JetBrains decompiler
// Type: sierses.SimHap.SettingsControl
// MVID: E01F66FE-3F59-44B4-8EBC-5ABAA8CD8267

using System.Windows;
using System.Windows.Controls;

namespace sierses.SimHap
{
	public partial class SettingsControl : UserControl //, IComponentConnector
	{
		public SimHap Plugin { get; }
		// this.InitializeComponent() gets generated by vs from SettingsControl.xaml
		public SettingsControl() => InitializeComponent();

		public SettingsControl(SimHap plugin) : this()
		{
			Plugin = plugin;
			DataContext = Plugin;
			Version.Text = Plugin.PluginVersion;
		}

		private void Refresh_Click(object sender, RoutedEventArgs e)
		{
			Plugin.S.Id = "";
			SimHap.LoadFailCount = 0;
			SimHap.FetchStatus = APIStatus.Retry;
			SimHap.LoadStatus = DataStatus.None;
			SimHap.LoadFinish = !SimHap.LoadFinish;
		}

		private void Lock_Click(object sender, RoutedEventArgs e)
		{
			Plugin.Settings.Unlocked = !Plugin.Settings.Unlocked;
			Plugin.D.LockedText = Plugin.Settings.Unlocked ? "Lock" : "Unlock";
		}
	}
}
